INSERT INTO route (from_point_id, to_point_id, days) VALUES
('CHINA_TERMINAL_1', 'RUSSIA_TERMINAL_3', 1),
('RUSSIA_TERMINAL_3', 'BELORUS_TERMINAL_1', 2),
('BELORUS_TERMINAL_1', 'POLAND_TERMINAL_1', 3),
('CHINA_TERMINAL_1', 'MONGLIA_TERMINAL_2', 4),
('CHINA_TERMINAL_1', 'KAZAKHSTAN_TERMINAL_2', 4),
('MONGLIA_TERMINAL_2', 'BELORUS_TERMINAL_1', 5),
('JAPAN_TERMINAL_1', 'RUSSIA_PORT_2', 7),
('RUSSIA_PORT_2', 'BELORUS_TERMINAL_1', 8),
('BELORUS_TERMINAL_1', 'GERMANY_TERMINAL_1', 9),
('BELORUS_TERMINAL_1', 'NETHERLANDS_TERMINAL_1', 10),
('KOREA_TERMINAL_1', 'RUSSIA_PORT_3', 11),
('RUSSIA_PORT_3', 'BELORUS_TERMINAL_1', 13),
('KAZAKHSTAN_TERMINAL_2', 'BELORUS_TERMINAL_1', 14),
('BELORUS_TERMINAL_1','CHZECH_TERMINAL_1',15)
ON CONFLICT DO NOTHING;
