INSERT INTO practice_two_step (id, name) values
(1, 'BETS_TABLE'),
(2, 'CONTAINER_CALCULATIONS_TABLE'),
(3, 'CONTAINERS_COUNT_TABLE'),
(4, 'MAP_ROUTES_TABLE'),
(5, 'BETS_DAYS_RISKS_TABLE'),
(6, 'ROUTES_CALCULATIONS_TABLE'),
(7, 'TOTAL_PRICES_TABLE');