version: '3'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

#  api:
#    build: ./
#    ports:
#      - "3001:3001"
#    restart: always
#    container_name: api
#    env_file:
#      - .env
#    command: bash -c "python3 src/init_and_wait_for_mongo.py && cd src && uvicorn main:api_app --port 80"
#    depends_on:
#      - db

#  redis:
#    image: "redis:latest"
#    ports:
#      - "6379:6379"
