version: '3'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build: ./
    ports:
      - "80:80"
    restart: always
    container_name: api
    env_file:
      - .env
    command: bash -c "python3 src/init_and_wait_for_mongo.py && cd src && uvicorn main:app --host 0.0.0.0 --port 80"
