version: '3'
services:
  db:
    restart: always
    container_name: db
    image: postgres:11.13
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    command: postgres -c stats_temp_directory=/tmp

  api:
    build: .
    ports:
      - "3001:3001"
      - "3002:3002"
    restart: always
    container_name: api
    env_file:
      - .env
    command: bash -c "sleep 7 && python3 src/wait_for_postgres.py && python3 src/main.py"
    depends_on:
      - db

  redis:
    image: redis:latest
    expose:
      - "6379:6379"
    restart: unless-stopped
