class MapResponse:
    start_point_code: str  # point_code
    end_point_code: str  # point_code
    route_length: int  # len of route
    points_codes_to_show: list[str]  # list of all points that should be visible on the map
    right_route_codes: list[str]  # the right route ( ordered ). codes of points

all_points = [
    {'code': 'CHINA_SHIJIAZHUANG_DEPARTURE_POINT', 'country': 'Китай', 'city': 'Шицзячжуан', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'CHINA_JINAN_DEPARTURE_POINT', 'country': 'Китай', 'city': 'Цзинань', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'CHINA_YIWU_DEPARTURE_POINT', 'country': 'Китай', 'city': 'Иу', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'CHINA_BAODING_DEPARTURE_POINT', 'country': 'Китай', 'city': 'Баодин', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'JAPAN_KYOTO_DEPARTURE_POINT', 'country': 'Япония', 'city': 'Киото', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'JAPAN_AYABE_DEPARTURE_POINT', 'country': 'Япония', 'city': 'Аябе', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'JAPAN_ASAGO_DEPARTURE_POINT', 'country': 'Япония', 'city': 'Асаго', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'JAPAN_MATSUMOTO_DEPARTURE_POINT', 'country': 'Япония', 'city': 'Мацумото', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'SOUTH_KOREA_SUWON_SI_DEPARTURE_POINT', 'country': 'Южная Корея', 'city': 'Сувон', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'SOUTH_KOREA_DAEJEON_DEPARTURE_POINT', 'country': 'Южная Корея', 'city': 'Тэджон', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'SOUTH_KOREA_CHANGWON_SI_DEPARTURE_POINT', 'country': 'Южная Корея', 'city': 'Чханвон', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'SOUTH_KOREA_GWANGJU_DEPARTURE_POINT', 'country': 'Южная Корея', 'city': 'Кванджу', 'type': 'DEPARTURE_POINT', 'is_fake': False},
    {'code': 'POLAND_LODZ_DESTINATION_POINT', 'country': 'Польша', 'city': 'Лодзь', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'POLAND_OSTRAVA_DESTINATION_POINT', 'country': 'Польша', 'city': 'Острава', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'GERMAN_LEIPZIG_DESTINATION_POINT', 'country': 'Германия', 'city': 'Лейпциг', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'GERMAN_AUGSBURG_DESTINATION_POINT', 'country': 'Германия', 'city': 'Аугсбург', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'FRANCE_LYON_DESTINATION_POINT', 'country': 'Франция', 'city': 'Лион', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'FRANCE_ROUEN_DESTINATION_POINT', 'country': 'Франция', 'city': 'Руан', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'NETHERLANDS_UTRETCH_DESTINATION_POINT', 'country': 'Нидерланды', 'city': 'Утрехт', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'NETHERLANDS_HARLEM_DESTINATION_POINT', 'country': 'Нидерланды', 'city': 'Харлем', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'BELGIUM_LEUVEN_DESTINATION_POINT', 'country': 'Бельгия', 'city': 'Лёвен', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'BELGIUM_GENT_DESTINATION_POINT', 'country': 'Бельгия', 'city': 'Гент', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'CZECH_PARDUBICE_DESTINATION_POINT', 'country': 'Чехия', 'city': 'Пардубице', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'CZECH_PILSEN_DESTINATION_POINT', 'country': 'Чехия', 'city': 'Пльзень', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'AUSTRIA_LINZ_DESTINATION_POINT', 'country': 'Австрия', 'city': 'Линц', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'AUSTRIA_SAINT_POLTEN_DESTINATION_POINT', 'country': 'Австрия', 'city': 'Санкт-Пёльтен', 'type': 'DESTINATION_POINT', 'is_fake': False},
    {'code': 'CHINA_GUANGZHOU_PORT', 'country': 'Китай', 'city': 'Гуанчжоу', 'type': 'PORT', 'is_fake': False},
    {'code': 'CHINA_NINGBO_PORT', 'country': 'Китай', 'city': 'Нинбо', 'type': 'PORT', 'is_fake': False},
    {'code': 'CHINA_CHONGQING_PORT', 'country': 'Китай', 'city': 'Чунцин', 'type': 'PORT', 'is_fake': False},
    {'code': 'CHINA_QINGDAO_PORT', 'country': 'Китай', 'city': 'Циндао', 'type': 'PORT', 'is_fake': False},
    {'code': 'JAPAN_AKITA_PORT', 'country': 'Япония', 'city': 'Акита', 'type': 'PORT', 'is_fake': False},
    {'code': 'JAPAN_YOKOHAMA_PORT', 'country': 'Япония', 'city': 'Йокогама', 'type': 'PORT', 'is_fake': False},
    {'code': 'JAPAN_KOBE_PORT', 'country': 'Япония', 'city': 'Кобе', 'type': 'PORT', 'is_fake': False},
    {'code': 'JAPAN_NAGOYA_PORT', 'country': 'Япония', 'city': 'Нагоя', 'type': 'PORT', 'is_fake': False},
    {'code': 'SOUTH_KOREA_PUSAN_PORT', 'country': 'Южная Корея', 'city': 'Пусан', 'type': 'PORT', 'is_fake': False},
    {'code': 'SOUTH_KOREA_INCHON_PORT', 'country': 'Южная Корея', 'city': 'Инчон', 'type': 'PORT', 'is_fake': False},
    {'code': 'RUSSIA_VLADIVOSTOK_PORT', 'country': 'Россия', 'city': 'Владивосток', 'type': 'PORT', 'is_fake': False},
    {'code': 'RUSSIA_VOSTOCHNYI_PORT', 'country': 'Россия', 'city': 'Восточный', 'type': 'PORT', 'is_fake': False},
    {'code': 'BELARUS_BREST_BORDER', 'country': 'Беларусь', 'city': 'Брест', 'type': 'BORDER', 'is_fake': False},
    {'code': 'KAZAKHSTAN_DOSTIK_BORDER', 'country': 'Казахстан', 'city': 'Достык', 'type': 'BORDER', 'is_fake': False},
    {'code': 'UZBEKISTAN_ALTUNKUL_BORDER', 'country': 'Казахстан', 'city': 'Алтынколь', 'type': 'BORDER', 'is_fake': False},
    {'code': 'RUSSIA_NAUSHKI_BORDER', 'country': 'Россия', 'city': 'Наушки', 'type': 'BORDER', 'is_fake': False},
    {'code': 'RUSSIA_ZABAIKALSK_BORDER', 'country': 'Россия', 'city': 'Забайкальск', 'type': 'BORDER', 'is_fake': False},
    # FAKE PORTS
    {'code': 'FAKE_INDIA_MUMBAI_PORT', 'country': 'Индия', 'city': 'Мумбаи', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_IRAN_BENDER_ABBAS_PORT', 'country': 'Иран', 'city': 'Бендер-Аббас', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_GEORGIA_POTI_PORT', 'country': 'Грузия', 'city': 'Поти', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_ROMANIA_CONSTANCA_PORT', 'country': 'Румыния', 'city': 'Констанца', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_BULGAR_BURGAS_PORT', 'country': 'Булгария', 'city': 'Бургас', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_KALININGRAD_PORT', 'country': 'Россия', 'city': 'Калининград', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_SPB_PORT', 'country': 'Россия', 'city': 'Санкт-Петербург', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_ARCHANGELSK_PORT', 'country': 'Россия', 'city': 'Архангельск', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_PETROPAVLIK_PORT', 'country': 'Россия', 'city': 'Петропавловск-Камчатский', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_EGYPT_ALEKSANDIA_PORT', 'country': 'Египет', 'city': 'Александрия', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_FRANCE_MARSEL_PORT', 'country': 'Франция', 'city': 'Марсель', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_GERMAN_GAMBURG_PORT', 'country': 'Германия', 'city': 'Гамбург', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_NETHERLANDS_ROTERDAM_PORT', 'country': 'Нидерланды', 'city': 'Роттердам', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_NOVOROSSISK_PORT', 'country': 'Россия', 'city': 'Новороссийск', 'type': 'PORT', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_ASTRACHAN_PORT', 'country': 'Россия', 'city': 'Астрахань', 'type': 'PORT', 'is_fake': True},
    # FAKE TERMINALS
    {'code': 'FAKE_BELARUS_MINSK_TERMINAL', 'country': 'Беларусь', 'city': 'Минск', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_EKB_TERMINAL', 'country': 'Россия', 'city': 'Екатеринбург', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_TOMSK_TERMINAL', 'country': 'Россия', 'city': 'Томск', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_NOVOSIB_TERMINAL', 'country': 'Россия', 'city': 'Новосибирск', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_KRASNOYARSK_TERMINAL', 'country': 'Россия', 'city': 'Красноярск', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_IRKUTSK_TERMINAL', 'country': 'Россия', 'city': 'Иркутск', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_HABAROVSK_TERMINAL', 'country': 'Россия', 'city': 'Хабаровск', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_ORENBURG_TERMINAL', 'country': 'Россия', 'city': 'Оренбург', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_SAMARA_TERMINAL', 'country': 'Россия', 'city': 'Самара', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_SARATOV_TERMINAL', 'country': 'Россия', 'city': 'Саратов', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_KAZAN_TERMINAL', 'country': 'Россия', 'city': 'Казань', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_NIZNOVGOROD_TERMINAL', 'country': 'Россия', 'city': 'Нижний Новгород', 'type': 'TERMINAL', 'is_fake': True},
    {'code': 'FAKE_RUSSIA_YAKUTSK_TERMINAL', 'country': 'Россия', 'city': 'Якутск', 'type': 'TERMINAL', 'is_fake': True},
]
