from schemas import (
    PR2ClassInfo,
    PR2Risk,
)

raw_pr2_clas_info = {
    'legend': """Компания имеет производственные мощности в Китае, отправляя свою продукцию в Европу преимущественно морским транспортом в 20-футовых контейнерах с продолжительностью доставки более 40 суток.
С учётом значительной продолжительности доставки продукции и случившегося кризиса у поставщика транспортных услуг, от существующей схемы Компания планирует отказаться. 
Кроме того, в условиях увеличения спроса на производимую продукцию Компания расширила географию присутствия, разместив дополнительные производственные мощности в Японии и Южной Корее и рассматривает новые цепи поставок продукции.
В связи с повышением привлекательности ускоренных контейнерных сервисов через Казахстан, Монголию и Россию, Компания планирует использовать новые маршруты и технологии доставки продукции. 
Перед Логистическим департаментом поставлена задача поиска оптимальных маршрутов цепей поставок продукции в страны Европы. Выполнение задачи поручено группе инициативных логистов.""",
    'explanation': """Вы представляете сотрудника Логистического департамента Компании. Для выполнения поставленной задачи необходимо:
1.	Учитывая, что перевозка осуществлялась в 20-футовых контейнерах, обосновать эффективность использования 40-футовых контейнеров с учётом максимального использования их вместимости и грузоподъемности 
2.	Рассчитать необходимое количество 40-футовых контейнеров для каждой цепи поставок продукции
3.	Сформировать возможные маршруты доставки 
4.	Детализировать маршруты по порядку проследования через транзитные страны 
5.	Рассчитать стоимость вариантов доставки для всех маршрутов по представленным ставкам логистических провайдеров 
6.	Выбрать риски организации доставки для всех маршрутов
7.	Выбрать минимальное по стоимости предложение провайдера и оптимальную комбинацию предложений по всем цепям поставок продукции
8.	Дать рекомендации по реализации вариантов с учетом рисков""",
    'steps_codes': [
        'SCREEN_1_INSTRUCTION_WITH_LEGEND',
        'SCREEN_2_TASK_DESCRIPTION',
        'SCREEN_3_SOURCE_DATA_FULL_ROUTES',
        'SCREEN_4_20_FOOT_CONTAINER_1_LOADING_VOLUME',
        'SCREEN_4_20_FOOT_CONTAINER_2_PACKAGE_VOLUME',
        'SCREEN_4_20_FOOT_CONTAINER_3_PACKAGE_NUMBER',
        'SCREEN_4_20_FOOT_CONTAINER_4_CAPACITY_UTILIZATION',
        'SCREEN_4_20_FOOT_CONTAINER_5_LOAD_CAPACITY',
        'SCREEN_4_40_FOOT_CONTAINER_1_LOADING_VOLUME',
        'SCREEN_4_40_FOOT_CONTAINER_2_PACKAGE_VOLUME',
        'SCREEN_4_40_FOOT_CONTAINER_3_PACKAGE_NUMBER',
        'SCREEN_4_40_FOOT_CONTAINER_4_CAPACITY_UTILIZATION',
        'SCREEN_4_40_FOOT_CONTAINER_5_LOAD_CAPACITY',
        'SCREEN_5_DESCRIBE_CONTAINER_SELECTION',
        'SCREEN_6_40_CONTAINERS_NUMBER_ROUTE_1',
        'SCREEN_6_40_CONTAINERS_NUMBER_ROUTE_2',
        'SCREEN_6_40_CONTAINERS_NUMBER_ROUTE_3',
        'SCREEN_6_40_CONTAINERS_NUMBER_ROUTE_4',
        'SCREEN_6_40_CONTAINERS_NUMBER_ROUTE_5',
        'SCREEN_7_SOURCE_DATA_CHOOSE_DESTINATIONS',
        'SCREEN_7_SOURCE_DATA_CHOOSE_PORTS',
        'SCREEN_7_SOURCE_DATA_CHOOSE_BORDER',
        'SCREEN_8_MAP_ROUTE_1',
        'SCREEN_8_MAP_ROUTE_2',
        'SCREEN_8_MAP_ROUTE_3',
        'SCREEN_8_MAP_ROUTE_4',
        'SCREEN_8_MAP_ROUTE_5',
        'SCREEN_8_MAP_ROUTE_6',
        'SCREEN_8_MAP_ROUTE_7',
        'SCREEN_8_MAP_ROUTE_8',
        'SCREEN_9_FORMED_ROUTES_TABLE',
        'SCREEN_10_RISKS_1',
        'SCREEN_10_RISKS_2',
        'SCREEN_10_RISKS_3',
        'SCREEN_10_RISKS_4',
        'SCREEN_10_RISKS_TOTAL',
        'SCREEN_10_FULL_ROUTES_WITH_PLS',
        'SCREEN_11_OPTIMAL_RESULTS_3PL1',
        'SCREEN_11_OPTIMAL_RESULTS_3PL2',
        'SCREEN_11_OPTIMAL_RESULTS_3PL3',
        'SCREEN_11_OPTIMAL_RESULTS_COMBO',
        'SCREEN_13_CHOOSE_LOGIST',
    ],
    'all_points': [
        {
            'code': 'CHINA_SHIJIAZHUANG_DEPARTURE_POINT',
            'country': 'Китай',
            'city': 'Шицзячжуан',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'CHINA_JINAN_DEPARTURE_POINT',
            'country': 'Китай',
            'city': 'Цзинань',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'CHINA_YIWU_DEPARTURE_POINT',
            'country': 'Китай',
            'city': 'Иу',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'CHINA_BAODING_DEPARTURE_POINT',
            'country': 'Китай',
            'city': 'Баодин',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'JAPAN_KYOTO_DEPARTURE_POINT',
            'country': 'Япония',
            'city': 'Киото',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'JAPAN_AYABE_DEPARTURE_POINT',
            'country': 'Япония',
            'city': 'Аябе',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'JAPAN_ASAGO_DEPARTURE_POINT',
            'country': 'Япония',
            'city': 'Асаго',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'JAPAN_MATSUMOTO_DEPARTURE_POINT',
            'country': 'Япония',
            'city': 'Мацумото',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'SOUTH_KOREA_SUWON_SI_DEPARTURE_POINT',
            'country': 'Южная Корея',
            'city': 'Сувон',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'SOUTH_KOREA_DAEJEON_DEPARTURE_POINT',
            'country': 'Южная Корея',
            'city': 'Тэджон',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'SOUTH_KOREA_CHANGWON_SI_DEPARTURE_POINT',
            'country': 'Южная Корея',
            'city': 'Чханвон',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'SOUTH_KOREA_GWANGJU_DEPARTURE_POINT',
            'country': 'Южная Корея',
            'city': 'Кванджу',
            'type': 'DEPARTURE_POINT',
            'is_fake': False,
        },
        {
            'code': 'POLAND_LODZ_DESTINATION_POINT',
            'country': 'Польша',
            'city': 'Лодзь',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'POLAND_OSTRAVA_DESTINATION_POINT',
            'country': 'Польша',
            'city': 'Острава',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'GERMAN_LEIPZIG_DESTINATION_POINT',
            'country': 'Германия',
            'city': 'Лейпциг',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'GERMAN_AUGSBURG_DESTINATION_POINT',
            'country': 'Германия',
            'city': 'Аугсбург',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'FRANCE_LYON_DESTINATION_POINT',
            'country': 'Франция',
            'city': 'Лион',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'FRANCE_ROUEN_DESTINATION_POINT',
            'country': 'Франция',
            'city': 'Руан',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'NETHERLANDS_UTRETCH_DESTINATION_POINT',
            'country': 'Нидерланды',
            'city': 'Утрехт',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'NETHERLANDS_HARLEM_DESTINATION_POINT',
            'country': 'Нидерланды',
            'city': 'Харлем',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'BELGIUM_LEUVEN_DESTINATION_POINT',
            'country': 'Бельгия',
            'city': 'Лёвен',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'BELGIUM_GENT_DESTINATION_POINT',
            'country': 'Бельгия',
            'city': 'Гент',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'CZECH_PARDUBICE_DESTINATION_POINT',
            'country': 'Чехия',
            'city': 'Пардубице',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'CZECH_PILSEN_DESTINATION_POINT',
            'country': 'Чехия',
            'city': 'Пльзень',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'AUSTRIA_LINZ_DESTINATION_POINT',
            'country': 'Австрия',
            'city': 'Линц',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {
            'code': 'AUSTRIA_SAINT_POLTEN_DESTINATION_POINT',
            'country': 'Австрия',
            'city': 'Санкт-Пёльтен',
            'type': 'DESTINATION_POINT',
            'is_fake': False,
        },
        {'code': 'CHINA_GUANGZHOU_PORT', 'country': 'Китай', 'city': 'Гуанчжоу', 'type': 'PORT', 'is_fake': False},
        {'code': 'CHINA_NINGBO_PORT', 'country': 'Китай', 'city': 'Нинбо', 'type': 'PORT', 'is_fake': False},
        {'code': 'CHINA_CHONGQING_PORT', 'country': 'Китай', 'city': 'Чунцин', 'type': 'PORT', 'is_fake': False},
        {'code': 'CHINA_QINGDAO_PORT', 'country': 'Китай', 'city': 'Циндао', 'type': 'PORT', 'is_fake': False},
        {'code': 'JAPAN_AKITA_PORT', 'country': 'Япония', 'city': 'Акита', 'type': 'PORT', 'is_fake': False},
        {'code': 'JAPAN_YOKOHAMA_PORT', 'country': 'Япония', 'city': 'Йокогама', 'type': 'PORT', 'is_fake': False},
        {'code': 'JAPAN_KOBE_PORT', 'country': 'Япония', 'city': 'Кобе', 'type': 'PORT', 'is_fake': False},
        {'code': 'JAPAN_NAGOYA_PORT', 'country': 'Япония', 'city': 'Нагоя', 'type': 'PORT', 'is_fake': False},
        {'code': 'SOUTH_KOREA_PUSAN_PORT', 'country': 'Южная Корея', 'city': 'Пусан', 'type': 'PORT', 'is_fake': False},
        {
            'code': 'SOUTH_KOREA_INCHON_PORT',
            'country': 'Южная Корея',
            'city': 'Инчон',
            'type': 'PORT',
            'is_fake': False,
        },
        {
            'code': 'RUSSIA_VLADIVOSTOK_PORT',
            'country': 'Россия',
            'city': 'Владивосток',
            'type': 'PORT',
            'is_fake': False,
        },
        {'code': 'RUSSIA_VOSTOCHNYI_PORT', 'country': 'Россия', 'city': 'Восточный', 'type': 'PORT', 'is_fake': False},
        {'code': 'BELARUS_BREST_BORDER', 'country': 'Беларусь', 'city': 'Брест', 'type': 'BORDER', 'is_fake': False},
        {
            'code': 'KAZAKHSTAN_DOSTIK_BORDER',
            'country': 'Казахстан',
            'city': 'Достык',
            'type': 'BORDER',
            'is_fake': False,
        },
        {
            'code': 'UZBEKISTAN_ALTUNKUL_BORDER',
            'country': 'Казахстан',
            'city': 'Алтынколь',
            'type': 'BORDER',
            'is_fake': False,
        },
        {'code': 'RUSSIA_NAUSHKI_BORDER', 'country': 'Россия', 'city': 'Наушки', 'type': 'BORDER', 'is_fake': False},
        {
            'code': 'RUSSIA_ZABAIKALSK_BORDER',
            'country': 'Россия',
            'city': 'Забайкальск',
            'type': 'BORDER',
            'is_fake': False,
        },
        # FAKE PORTS
        {'code': 'FAKE_INDIA_MUMBAI_PORT', 'country': 'Индия', 'city': 'Мумбаи', 'type': 'PORT', 'is_fake': True},
        {
            'code': 'FAKE_IRAN_BENDER_ABBAS_PORT',
            'country': 'Иран',
            'city': 'Бендер-Аббас',
            'type': 'PORT',
            'is_fake': True,
        },
        {'code': 'FAKE_GEORGIA_POTI_PORT', 'country': 'Грузия', 'city': 'Поти', 'type': 'PORT', 'is_fake': True},
        {
            'code': 'FAKE_ROMANIA_CONSTANCA_PORT',
            'country': 'Румыния',
            'city': 'Констанца',
            'type': 'PORT',
            'is_fake': True,
        },
        {'code': 'FAKE_BULGAR_BURGAS_PORT', 'country': 'Булгария', 'city': 'Бургас', 'type': 'PORT', 'is_fake': True},
        {
            'code': 'FAKE_RUSSIA_KALININGRAD_PORT',
            'country': 'Россия',
            'city': 'Калининград',
            'type': 'PORT',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_SPB_PORT',
            'country': 'Россия',
            'city': 'Санкт-Петербург',
            'type': 'PORT',
            'is_fake': True,
        },
        {
            'code': 'FAKE_EGYPT_ALEKSANDIA_PORT',
            'country': 'Египет',
            'city': 'Александрия',
            'type': 'PORT',
            'is_fake': True,
        },
        {'code': 'FAKE_FRANCE_MARSEL_PORT', 'country': 'Франция', 'city': 'Марсель', 'type': 'PORT', 'is_fake': True},
        {'code': 'FAKE_GERMAN_GAMBURG_PORT', 'country': 'Германия', 'city': 'Гамбург', 'type': 'PORT', 'is_fake': True},
        {
            'code': 'FAKE_NETHERLANDS_ROTERDAM_PORT',
            'country': 'Нидерланды',
            'city': 'Роттердам',
            'type': 'PORT',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_NOVOROSSISK_PORT',
            'country': 'Россия',
            'city': 'Новороссийск',
            'type': 'PORT',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_ASTRACHAN_PORT',
            'country': 'Россия',
            'city': 'Астрахань',
            'type': 'PORT',
            'is_fake': True,
        },
        # FAKE TERMINALS
        {
            'code': 'FAKE_BELARUS_MINSK_TERMINAL',
            'country': 'Беларусь',
            'city': 'Минск',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_EKB_TERMINAL',
            'country': 'Россия',
            'city': 'Екатеринбург',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_TOMSK_TERMINAL',
            'country': 'Россия',
            'city': 'Томск',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_NOVOSIB_TERMINAL',
            'country': 'Россия',
            'city': 'Новосибирск',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_KRASNOYARSK_TERMINAL',
            'country': 'Россия',
            'city': 'Красноярск',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_IRKUTSK_TERMINAL',
            'country': 'Россия',
            'city': 'Иркутск',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_HABAROVSK_TERMINAL',
            'country': 'Россия',
            'city': 'Хабаровск',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_ORENBURG_TERMINAL',
            'country': 'Россия',
            'city': 'Оренбург',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_SAMARA_TERMINAL',
            'country': 'Россия',
            'city': 'Самара',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_SARATOV_TERMINAL',
            'country': 'Россия',
            'city': 'Саратов',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_KAZAN_TERMINAL',
            'country': 'Россия',
            'city': 'Казань',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_NIZNOVGOROD_TERMINAL',
            'country': 'Россия',
            'city': 'Нижний Новгород',
            'type': 'TERMINAL',
            'is_fake': True,
        },
        {
            'code': 'FAKE_RUSSIA_YAKUTSK_TERMINAL',
            'country': 'Россия',
            'city': 'Якутск',
            'type': 'TERMINAL',
            'is_fake': True,
        },
    ],
}

risks = [
    [
        PR2Risk(text='Простой контейнеров в ожидании перегрузки\nпо причине занятости инфраструктуры', id=1),
        PR2Risk(text='Неполная информация в товаро-сопроводительных документах', id=2),
        PR2Risk(text='Ожидание подвижного состава под перегрузку контейнеров', id=3),
        PR2Risk(text='Административные запреты пропуска грузов\nна погранпереходе', id=4),
        PR2Risk(text='Простои вагонов в ожидании погрузочно-разгрузочных операций', id=5),
        PR2Risk(text='Повреждение груза водой, пожаром или механическим воздействием', id=6),
        PR2Risk(text='Простой контейнеров на терминале по причине неисправности кранового оборудования', id=7),
        PR2Risk(text='Технологические простои на станции отправления\nпри формировании поезда', id=8),
        PR2Risk(text='Ожидание подачи поездного локомотива', id=9),
        PR2Risk(text='Выявленная при осмотре техническая неисправность контейнера', id=10),
    ],
    [
        PR2Risk(text='Отсутствие разрешительных документов', id=11),
        PR2Risk(text='Ожидание подвижного состава под перегрузку контейнеров', id=12),
        PR2Risk(text='Непредвиденное снижение объема заявки на покупку продукции', id=13),
        PR2Risk(text='Увеличение времени погрузки по причине ухудшения погодных условий', id=14),
        PR2Risk(text='Техническая неисправность поданных под погрузку вагонов', id=15),
        PR2Risk(text='Технологические простои на станции назначения\nпри расформировании поезда', id=16),
        PR2Risk(
            text='Снижение пропускной способности по причине ремонтно-восстановительных работ на участке железной дороги',
            id=17,
        ),
        PR2Risk(text='Снижение пропускной способности по причине ремонта участка автомобильной дороги', id=18),
        PR2Risk(text='Неисправность досмотрового оборудования\nна терминале', id=19),
        PR2Risk(text='Повреждение контейнера при перегрузке', id=20),
    ],
    [
        PR2Risk(text='Административные запреты пропуска грузов\nна погранпереходе', id=21),
        PR2Risk(text='Выявленные нарушения при оформлении таможенных документов', id=22),
        PR2Risk(text='Подготовка дорог к весенней сушке', id=23),
        PR2Risk(text='Коммерческая неисправность поданных под погрузку вагонов', id=24),
        PR2Risk(text='Изменение курса валюты', id=25),
        PR2Risk(text='Очередь на МАПП', id=26),
        PR2Risk(text='Неполный комплект перевозочных документов', id=27),
        PR2Risk(text='Простой вагонов по причине занятости инфраструктуры', id=28),
        PR2Risk(text='Технологические простои при формировании поезда', id=29),
        PR2Risk(text='Потеря контейнера на терминале', id=30),
    ],
    [
        PR2Risk(text='Задержка прибытия судна по причине неисправности навигационного оборудования', id=31),
        PR2Risk(text='Посадка судна на мель', id=32),
        PR2Risk(text='Повреждение контейнера при перегрузке', id=33),
        PR2Risk(text='Смещение/опрокидывание контейнера\nпри выгрузке с судна ', id=34),
        PR2Risk(text='Простой в ожидании разгрузки по причине неисправности кранового оборудования', id=35),
        PR2Risk(text='Техническая и коммерческая неисправность поданных под погрузку вагонов', id=36),
        PR2Risk(text='Ухудшение погодных условий (ожидание разрешения\nна заход/выход из/в порт)', id=37),
        PR2Risk(text='Простои под выгрузкой с судна ', id=38),
        PR2Risk(text='Отсутствие вагонов под погрузку ', id=39),
        PR2Risk(
            text='Занятость путей припортовой станции, задержка подачи вследствие технологических проблем при подаче вагонов на погрузочно-выгрузочный путь',
            id=40,
        ),
    ],
]

pr2_class_info = PR2ClassInfo(**raw_pr2_clas_info, all_risks=risks)
